import type { PageDefinition } from "@factory/template-sdk";
import {
  creativeApproachId,
  creativeContactId,
  creativeContactPageId,
  creativeHeroId,
  creativeHomePageId,
  creativeProofId,
  creativeQuoteId,
  creativeServicesId,
  creativeWorkId,
  creativeWorkPageId,
} from "../ids";

export const creativePages: readonly PageDefinition[] = [
  {
    id: creativeHomePageId,
    title: "Home",
    slug: { kind: "fixed", defaultValue: "/", maximumLength: 1 },
    allowedSections: [
      creativeHeroId,
      creativeProofId,
      creativeWorkId,
      creativeServicesId,
      creativeApproachId,
      creativeQuoteId,
    ],
    requiredSections: [
      { sectionTypeId: creativeHeroId, minimum: 1, maximum: 1 },
      { sectionTypeId: creativeWorkId, minimum: 1, maximum: 1 },
    ],
    defaultSections: [
      { sectionTypeId: creativeHeroId },
      { sectionTypeId: creativeProofId },
      { sectionTypeId: creativeWorkId },
      { sectionTypeId: creativeServicesId },
      { sectionTypeId: creativeApproachId },
      { sectionTypeId: creativeQuoteId },
    ],
    supportsSEO: true,
    supportsNavigation: true,
    supportsIndexing: true,
    editor: { description: "Editorial portfolio landing page", icon: "home" },
  },
  {
    id: creativeWorkPageId,
    title: "Work",
    slug: { kind: "fixed", defaultValue: "work", maximumLength: 80 },
    allowedSections: [creativeWorkId, creativeQuoteId],
    requiredSections: [{ sectionTypeId: creativeWorkId, minimum: 1, maximum: 1 }],
    defaultSections: [{ sectionTypeId: creativeWorkId }, { sectionTypeId: creativeQuoteId }],
    supportsSEO: true,
    supportsNavigation: true,
    supportsIndexing: true,
    editor: { description: "Selected portfolio case studies", icon: "grid" },
  },
  {
    id: creativeContactPageId,
    title: "Contact",
    slug: { kind: "fixed", defaultValue: "contact", maximumLength: 80 },
    allowedSections: [creativeContactId],
    requiredSections: [{ sectionTypeId: creativeContactId, minimum: 1, maximum: 1 }],
    defaultSections: [{ sectionTypeId: creativeContactId }],
    supportsSEO: true,
    supportsNavigation: true,
    supportsIndexing: true,
    editor: { description: "Project enquiry and availability", icon: "mail" },
  },
];
